name: Zaliczenie Laboratorium na 5+

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-deploy:
    name: Buduję i publikuję kontener
    runs-on: ubuntu-latest

    steps:
      - name: Pobieram kod źródłowy z repozytorium
        uses: actions/checkout@v4

      - name: Konfiguruję Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Loguję się do DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buduję obraz kontenera (lokalnie, do Trivy)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          no-cache: true
          tags: marcin002/weather-app:${{ github.sha }}
          cache-from: type=registry,ref=marcin002/weather-app:cache
          cache-to: type=registry,ref=marcin002/weather-app:cache,mode=max
          build-args: |
            VERSION=1.0.0

      - name: Czyszczę cache Trivy
        run: rm -rf ~/.cache/trivy

      - name: Skanuję obraz pod kątem luk bezpieczeństwa (CVE)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: marcin002/weather-app:${{ github.sha }}
          format: table
          exit-code: 1
          vuln-type: os,library
          ignore-unfixed: false
          severity: CRITICAL,HIGH

      - name: Wypycham obraz na DockerHub (jeśli bezpieczny)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: marcin002/weather-app:${{ github.sha }},marcin002/weather-app:latest
          cache-from: type=registry,ref=marcin002/weather-app:cache
          cache-to: type=registry,ref=marcin002/weather-app:cache,mode=max
          build-args: |
            VERSION=1.0.0
